InsTerm/Models/Zlecenie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InsTerm.Models
{
    public class Zlecenie
    {
        public long id { get; set; }
        public string name { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string terminal { get; set; }
        public string installDate { get; set; }
        public string status { get; set; }
    }
}

InsTerm/Controllers/ZLECENIEController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace InsTerm.Controllers
{
    [Authorize(Roles ="Operacje,Administrator,Instalator")]
    public class ZLECENIEController : Controller
    {
        private DB_Entities db = new DB_Entities();

        // GET: ZLECENIE
        public ActionResult Index()
        {
            if (User.IsInRole("Instalator"))
            {
                var zLECENIE = db.ZLECENIE
                        .Include(z => z.MERCHANT)
                        .Include(z => z.SIM)
                        .Include(z => z.TERMINAL)
                        .Where(z => z.ZL_USER == User.Identity.Name)
                        .OrderByDescending(z => z.ZL_INSTALLDATE).ToList();
                return View(zLECENIE);
            }
            else
            {
                var zLECENIE = db.ZLECENIE
                        .Include(z => z.MERCHANT)
                        .Include(z => z.SIM)
                        .Include(z => z.TERMINAL)
                        .OrderByDescending(z => z.ZL_INSTALLDATE);
                return View(zLECENIE.ToList());
            }

        }

        // GET: ZLECENIE/Details/5
        public ActionResult Details(long? id)
        {
            ZLECENIE zLECENIE;


            if (User.IsInRole("Instalator"))
            {
                zLECENIE = db.ZLECENIE
                    .Include(z => z.MERCHANT)
                    .Include(z => z.SIM)
                    .Include(z => z.PERIPHERALS)
                    .Include(z => z.TERMINAL)
                    .Include(z => z.TERMINAL_APP)
                    .Where(z => z.ZL_ID == id && z.ZL_USER == User.Identity.Name)
                    .FirstOrDefault();
            }
            else
            {
                zLECENIE = db.ZLECENIE
                    .Include(z => z.MERCHANT)
                    .Include(z => z.SIM)
                    .Include(z => z.PERIPHERALS)
                    .Include(z => z.TERMINAL)
                    .Include(z => z.TERMINAL_APP)
                    .Where(z => z.ZL_ID == id)
                    .FirstOrDefault();
            }


            if (zLECENIE == null)
            {
                return RedirectToAction("Index");
            }
            return View(zLECENIE);
        }

        // GET: ZLECENIE/Create
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Create()
        {


            var roles = (from r in db.v_UserRoles
                         where r.ROLENAME=="Instalator"
                         select r).ToList();
            SelectList list = new SelectList(roles, "USERNAME", "USERNAME");

            var terminale = (from t in db.TERMINAL
                             where t.ZLECENIE.Count() == 0
                             select t).ToList();
            SelectList terminalList = new SelectList(terminale, "T_ID", "T_SERIAL");

            var karty = (from s in db.SIM
                         where s.ZLECENIE.Count() == 0
                         select s).ToList();
            SelectList simList = new SelectList(karty, "SIM_IMEI", "SIM_IMEI");

            ViewBag.ZL_MID = new SelectList(db.MERCHANT, "M_ID", "M_NAME");
            ViewBag.ZL_SIM = simList;
            ViewBag.ZL_TID = terminalList;
            ViewBag.ZL_APP = new SelectList(db.TERMINAL_APP, "TA_ID", "TA_NAME");
            ViewBag.ZL_USER = list;
            return View();
        }

        // POST: ZLECENIE/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Create(FormCollection collection)
        {
            string frmTID = collection.Get("ZL_TID");


            string frmMID = collection.Get("ZL_MID");

            DateTime frmInstallDate = DateTime.Parse(collection.Get("ZL_INSTALLDATE"));
            string frmINFO = collection.Get("ZL_INFO");
            //ZL_STATUS

            string frmUser = collection.Get("ZL_USER");
            var user = db.AspNetUsers.Where(u => u.UserName == frmUser).First();
            if (user == null) return View();

            string frmSIM = collection.Get("ZL_SIM");

            ZLECENIE z = new ZLECENIE();

            long? newId = db.ZLECENIE.Max(zl => (long?)zl.ZL_ID);
            if (newId == null || newId == 0)
            { newId = 1; }
            else
            { newId = newId + 1; }
            z.ZL_ID = (long)newId;
            z.ZL_INFO = frmINFO;
            z.ZL_INSTALLDATE = frmInstallDate;
            z.ZL_MID = Int32.Parse(frmMID);
            z.ZL_STATUS = "N";
            z.ZL_SIM = frmSIM;
            z.ZL_USER = frmUser;
            z.ZL_TID = Int32.Parse(frmTID);

            try
            {
                db.ZLECENIE.Add(z);
                db.SaveChanges();
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message.ToString();
                return View();
            }

            return RedirectToAction("Details", new { id = z.ZL_ID });
        }

        // GET: ZLECENIE/Edit/5
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZLECENIE zLECENIE = db.ZLECENIE.Find(id);
            if (zLECENIE == null)
            {
                return RedirectToAction("Index");
            }


            var terminale = (from t in db.TERMINAL
                             where t.ZLECENIE.Count() == 0 || t.T_ID == id
                             select t).ToList();
            SelectList terminalList = new SelectList(terminale, "T_ID", "T_SERIAL");

            var karty = (from s in db.SIM
                         where s.ZLECENIE.Count() == 0 || s.SIM_IMEI == zLECENIE.ZL_SIM
                         select s).ToList();
            SelectList simList = new SelectList(karty, "SIM_IMEI", "SIM_IMEI");

            var instalatorzy = (from i in db.v_UserRoles 
                                where i.ROLENAME == "Instalator"
                                select i).ToList();
            SelectList instList = new SelectList(instalatorzy, "USERNAME", "USERNAME");

            SelectList statusList = new SelectList(
                new List<SelectListItem>
                {
                                new SelectListItem { Text = "Nowe (n)", Value = "n"},
                                new SelectListItem { Text = "W trakcie Przetwarzania (p)", Value = "p"},
                                new SelectListItem { Text = "Zakończone - udane (f)", Value = "f"},
                                new SelectListItem { Text = "Zakończone - nieudane (a)", Value = "a"},
                                new SelectListItem { Text = "Inne (u)", Value = "u"},
                }, "Value", "Text");


            ViewBag.ZL_MID = new SelectList(db.MERCHANT, "M_ID", "M_NAME", zLECENIE.ZL_MID);
            ViewBag.ZL_SIM = simList;
            ViewBag.ZL_TID = terminalList;
            ViewBag.ZL_USER = instList;
            ViewBag.ZL_STATUS = statusList;
            return View(zLECENIE);
        }

        // POST: ZLECENIE/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Edit(FormCollection collection)
        {
            int id = int.Parse(collection.Get("ZL_ID"));
            int tid = int.Parse(collection.Get("ZL_TID"));
            int mid = int.Parse(collection.Get("ZL_MID"));
            DateTime dte = DateTime.Parse(collection.Get("ZL_INSTALLDATE"));
            string info = collection.Get("ZL_INFO");
            string status = collection.Get("ZL_STATUS");

            string instuser = collection.Get("ZL_USER");

            string simImei = collection.Get("ZL_SIM");

            ZLECENIE zLECENIE = db.ZLECENIE.Where(z => z.ZL_ID == id).First();
            if (zLECENIE == null) return RedirectToAction("Index");

            zLECENIE.ZL_INFO = info;
            zLECENIE.ZL_INSTALLDATE = dte;
            zLECENIE.ZL_MID = mid;
            zLECENIE.ZL_SIM = simImei;
            zLECENIE.ZL_STATUS = status;
            zLECENIE.ZL_TID = tid;
            zLECENIE.ZL_USER = instuser;

            try
            { 
                db.Entry(zLECENIE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = zLECENIE.ZL_ID });
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message.ToString();
            }

            var terminale = (from t in db.TERMINAL
                             where t.ZLECENIE.Count() == 0 || t.T_ID == id
                             select t).ToList();
            SelectList terminalList = new SelectList(terminale, "T_ID", "T_SERIAL");

            var karty = (from s in db.SIM
                         where s.ZLECENIE.Count() == 0 || s.SIM_IMEI == zLECENIE.ZL_SIM
                         select s).ToList();
            SelectList simList = new SelectList(karty, "SIM_IMEI", "SIM_IMEI");

            var instalatorzy = (from i in db.v_UserRoles
                                where i.ROLENAME == "Instalator"
                                select i).ToList();
            SelectList instList = new SelectList(instalatorzy, "USERNAME", "USERNAME");


            ViewBag.ZL_MID = new SelectList(db.MERCHANT, "M_ID", "M_NAME", zLECENIE.ZL_MID);
            ViewBag.ZL_SIM = simList;
            ViewBag.ZL_TID = terminalList;
            ViewBag.ZL_USER = instList;
            return View(zLECENIE);
        }

        [Authorize(Roles = "Instalator")]
        public ActionResult EditOwn(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

InsTerm/Views/ZLECENIE/AddApps.cshtml
@model InsTerm.TERMINAL_APP

@{
    ViewBag.Title = "AddApps";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj aplikacje</h2>
<h4>Zlecenie nr: @ViewBag.ZLID</h4>
<table class="table-bordered">
    <tr>
        <th>
            @Html.DisplayName("Aplikacja")
        </th>

    </tr>
    <tr>

    </tr>
</table>

InsTerm/Views/ZLECENIE/Create.cshtml
@model InsTerm.ZLECENIE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nowe zlecenie</h2>


@using (Html.BeginForm("Create", "ZLECENIE", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ZLECENIE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.ZL_ID, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <div class="form-group">
            @Html.Label("Terminal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZL_TID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZL_TID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Akceptant", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZL_MID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZL_MID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Planowana data instalacji".ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ZL_INSTALLDATE, new { @class = "form-control datepicker", placeholder = "Data", required = "required" })
                @Html.ValidationMessageFor(model => model.ZL_INSTALLDATE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dodatkowe informacje".ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZL_INFO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZL_INFO, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ZL_STATUS, new { htmlAttributes = new { @class = "form-control" } })

        <div class="form-group">
            @Html.Label("Instalator", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZL_USER", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZL_USER, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Karta SIM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZL_SIM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SIM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('.datepicker').datepicker(); //Initialise any date pickers
    </script>
}

InsTerm/Views/ZLECENIE/Delete.cshtml
@model InsTerm.ZLECENIE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>USUŃ ZLECENIE</h2>

<h3>Czy na pewno chcesz usunąć zlecenie?</h3>
<div>
    <h4>ZLECENIE @Model.ZL_ID - @Model.MERCHANT.M_NAME</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Planowana data instalacji")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_INSTALLDATE)
        </dd>

        <dt>
            @Html.DisplayName("Informacje")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_INFO)
        </dd>

        <dt>
            @Html.DisplayName("Status")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_STATUS)
        </dd>

        <dt>
            @Html.DisplayName("Instalator")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_USER)
        </dd>

        <dt>
            @Html.DisplayName("Karta SIM")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SIM.SIM_NETWORK)<br />
            @Html.DisplayFor(model => model.SIM.SIM_IMEI)<br />
            @Html.DisplayFor(model => model.SIM.SIM_MODE)
        </dd>

        <dt>
            @Html.DisplayName("Terminal")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TERMINAL.TERMINAL_MODEL.TM_NAME)<br />
            @Html.DisplayFor(model => model.TERMINAL.T_SERIAL)<br />
            @Html.DisplayFor(model => model.TERMINAL.T_NOTES)
        </dd>
        <dt>
            @Html.DisplayName("TID")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TERMINAL.T_ID)
        </dd>

        <br />
        <br />
        <br />
        <dt>
            @Html.DisplayName("Punkt instalacji")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MERCHANT.M_NAME)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_INFO)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_STREET)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_STREET2)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_CITY)<br />
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Kontakt do punktu")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MERCHANT.M_EMAIL)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_PHONE1)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_PHONE2)<br />
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń zlecenie" class="btn btn-default" /><br/><br/>
            @Html.ActionLink("Powrót do listy zleceń", "Index")
        </div>
    }
</div>

InsTerm/Views/ZLECENIE/Details.cshtml
@model InsTerm.ZLECENIE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ZLECENIE Instalacji</h2>

<div>
    <h4>@Model.MERCHANT.M_NAME</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Planowana data instalacji")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_INSTALLDATE)
        </dd>

        <dt>
            @Html.DisplayName("Informacje")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_INFO)
        </dd>

        <dt>
            @Html.DisplayName("Status")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_STATUS)
        </dd>

        <dt>
            @Html.DisplayName("Instalator")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZL_USER)
        </dd>

        <dt>
            @Html.DisplayName("Karta SIM")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SIM.SIM_NETWORK)<br />
            @Html.DisplayFor(model => model.SIM.SIM_IMEI)<br />
            @Html.DisplayFor(model => model.SIM.SIM_MODE)
        </dd>

        <dt>
            @Html.DisplayName("Terminal")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TERMINAL.TERMINAL_MODEL.TM_NAME)<br />
            @Html.DisplayFor(model => model.TERMINAL.T_SERIAL)<br />
            @Html.DisplayFor(model => model.TERMINAL.T_NOTES)
        </dd>
        <dt>
            @Html.DisplayName("TID")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TERMINAL.T_ID)
        </dd>

        <br />
        <br />
        <br />
        <dt>
            @Html.DisplayName("Punkt instalacji")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MERCHANT.M_NAME)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_INFO)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_STREET)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_STREET2)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_CITY)<br />
            </dd>
        <br/>
        <dt>
            @Html.DisplayName("Kontakt do punktu")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MERCHANT.M_EMAIL)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_PHONE1)<br />
            @Html.DisplayFor(model => model.MERCHANT.M_PHONE2)<br />
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Lista zleceń", "Index")
    @if (!User.IsInRole("Instalator"))
    {
        <b>&nbsp;|&nbsp;</b>
        @Html.ActionLink("Edycja", "Edit", new { id = Model.ZL_ID })
    }
    else
    {
        <b>&nbsp;|&nbsp;</b>
        @Html.ActionLink("Edycja", "EditOwn", new { id = Model.ZL_ID })
    }

</p>

InsTerm/Views/ZLECENIE/Edit.cshtml
@model InsTerm.ZLECENIE

@{
    ViewBag.Title = "Edycja zlecenia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EDYCJA</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ZLECENIE: @Model.ZL_ID</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ZL_ID)

    <div class="form-group">
        @Html.Label("Terminal ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ZL_TID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZL_TID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Akceptant", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ZL_MID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZL_MID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Planowana data instalacji", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZL_INSTALLDATE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZL_INSTALLDATE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Dodatkowe informacje", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZL_INFO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZL_INFO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Stan", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ZL_STATUS", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Instalator", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ZL_USER", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Karta Sim", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ZL_SIM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZL_SIM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/ZLECENIE/EditOwn.cshtml
@model InsTerm.ZLECENIE

@{
    ViewBag.Title = "Modyfikuj zlecenie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja zlecenia</h2>


@using (Html.BeginForm("EditOwn", "ZLECENIE", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ZLECENIE: @Model.ZL_ID</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ZL_ID)

        <div class="form-group">
            @Html.Label("Terminal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ZL_TID)&nbsp;&frasl;&nbsp;
                @Html.DisplayFor(model => model.TERMINAL.TERMINAL_MODEL.TM_NAME)&nbsp;&frasl;&nbsp;
                @Html.DisplayFor(model => model.TERMINAL.T_SERIAL)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Akceptant", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ZL_MID) &nbsp;&frasl;&nbsp;
                @Html.DisplayFor(model => model.MERCHANT.M_NAME)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Planowana data instalacji", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ZL_INSTALLDATE)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Uwagi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZL_INFO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZL_INFO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Zmień status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">

                @Html.DropDownList("ZL_ST", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.ZL_USER)
        </div>
        <br />
        <div class="form-group">
            @Html.Label("Karta SIM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.SIM.SIM_NETWORK) &nbsp;&frasl;&nbsp;
                @Html.DisplayFor(model => model.ZL_SIM)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy zleceń", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}