InsTerm/Controllers/TerminaleController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsTerm.Controllers
{
    [Authorize(Roles = "Operacje,Administrator")]
    public class TerminaleController : Controller
    {
        private DB_Entities _db = new DB_Entities();

        // GET: Terminale
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        public ActionResult List()
        {
            var model = _db.TERMINAL.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var modele = (from m in _db.TERMINAL_MODEL
                         select m).ToList();
            SelectList list = new SelectList(modele, "TM_ID", "TM_NAME");
            ViewBag.T_MODEL = list;
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind(Include = "T_ID, T_MODEL, T_SERIAL, T_NOTES")] TERMINAL terminal)
        {
            int exists = _db.TERMINAL.Where(t => t.T_ID == terminal.T_ID).Count();
            if (exists > 0)
            {
                TempData["Error"] = "Terminal o podanym numerze TID już istnieje!";
                return RedirectToAction("Create");
            }

            if (ModelState.IsValid)
            {
                _db.TERMINAL.Add(terminal);
                _db.SaveChanges();
                return RedirectToAction("List");
            }
            TempData["Error"] = "Błędne dane!";
            return View(terminal);
        }


        // MODELE

        public ActionResult ModelList()
        {
            var model = _db.TERMINAL_MODEL.ToList();
            return View(model);
        }
        public ActionResult ModelDetails(int? id)
        {
            if (id == null) return RedirectToAction("ModelList");

            var model = _db.TERMINAL_MODEL.Where(t => t.TM_ID == id).First();
            if (model == null) return RedirectToAction("ModelList");


            return View(model);
        }
        [HttpGet]
        public ActionResult AddModel()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddModel([Bind(Include = "TM_NAME, TM_DESC, TM_VERSION")] TERMINAL_MODEL terminalModel)
        {
            try
            {
                int newId = _db.TERMINAL_MODEL.Max(m => m.TM_ID);
                terminalModel.TM_ID = newId + 1;
            }
            catch (Exception ex)
            {
                ViewBag.Errors = "Nie udało się pobrać modelu";
                return View();
            }
            if (ModelState.IsValid)
            {
                _db.TERMINAL_MODEL.Add(terminalModel);
                _db.SaveChanges();
                return RedirectToAction("ModelList");
            }
            return View();
        }

        [HttpGet]
        public ActionResult EditModel(int? id)
        {
            if (id == null) return RedirectToAction("ModelList");

            var model = _db.TERMINAL_MODEL.Where(m => m.TM_ID == id).First();
            if (model == null) return RedirectToAction("ModelList");
            return View(model);
        }

        [HttpPost]
        public ActionResult EditModel([Bind(Include = "TM_ID, TM_NAME, TM_DESC, TM_VERSION")] TERMINAL_MODEL terminalModel)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(terminalModel).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("ModelList");
            }
            return View(terminalModel);
        }



        [HttpGet]
        public ActionResult DeleteModel(int? id)
        {
            var terminalModel = _db.TERMINAL_MODEL.Where(t => t.TM_ID == id).First();
            if (terminalModel == null)
            {
                TempData["Error"] = "Nie można usunąć modelu. Brak terminalu o takim numerze ID.";
                return View();
            }
            return View(terminalModel);
        }

        [HttpPost]
        public ActionResult DeleteModelConfirmed(FormCollection collection)
        {
            string modelId = collection.Get("TM_ID");
            if (String.IsNullOrEmpty(modelId))
            {
                TempData["Error"] = "Nie można usunąć - nie znaleziono urządzenia!";
                return RedirectToAction("ModelList");
            }
            int tid = Int32.Parse(modelId);
            int zl = _db.TERMINAL.Where(z => z.T_MODEL == tid).Count();
            if (zl > 0)
            {
                TempData["Error"] = "Nie można usunąć. Urządzenie przypisane jest już do co najmniej jednego terminalu.";
                return RedirectToAction("ModelList");
            }

            var terminalModelToDelete = _db.TERMINAL_MODEL.Where(t => t.TM_ID == tid).First();
            _db.Entry(terminalModelToDelete).State = EntityState.Deleted;
            _db.SaveChanges();
            return RedirectToAction("ModelList");
        }


        //public ActionResult Aplikacje()
        //{
        //    var model = _db.TERMINAL_APP.ToList();
        //    return View(model);
        //}


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null) return RedirectToAction("List");

            var terminal = _db.TERMINAL
                .Where(t => t.T_ID == id).First();
            ViewBag.T_MODEL = new SelectList(_db.TERMINAL_MODEL, "TM_ID", "TM_NAME", terminal.T_MODEL);
            return View(terminal);
        }


        [HttpPost]
        public ActionResult Edit([Bind(Include = "T_ID, T_MODEL, T_SERIAL, T_NOTES")] TERMINAL terminal)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(terminal).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = terminal.T_ID });
            }
            return View();
        }








        public ActionResult Details(int? id)
        {
            if (id == null) return RedirectToAction("List");

            var terminal = _db.TERMINAL
                .Include(t => t.TERMINAL_MODEL)
                .Where(t => t.T_ID == id).First();
            ViewBag.T_MODEL = new SelectList(_db.TERMINAL_MODEL, "TM_ID", "TM_NAME", terminal.T_MODEL);
            return View(terminal);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var terminal = _db.TERMINAL.Where(t => t.T_ID == id).First();
            if (terminal == null)
            {
                ViewBag.Error = "Nie można usunąć terminalu. Brak terminalu o takim numerze TID.";
                return View();
            }
            return View(terminal);
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(FormCollection collection)
        {
            string terminalId = collection.Get("TID");
            if (String.IsNullOrEmpty(terminalId))
            {
                TempData["Error"] = "Nie można usunąć - nie znaleziono terminalu!";
                return RedirectToAction("List");
            }
            int tid = Int32.Parse(terminalId);
            int zl = _db.ZLECENIE.Where(z => z.TERMINAL.T_ID == tid).Count();
            if (zl > 0)
            {
                TempData["Error"] = "Nie można usunąć. Do terminalu przypisane jest już zlecenie.";
                return RedirectToAction("List");
            }

            var terminalToDelete = _db.TERMINAL.Where(t => t.T_ID == tid).First();
                _db.Entry(terminalToDelete).State = EntityState.Deleted;
                _db.SaveChanges();
                return RedirectToAction("List");



        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsTerm/Views/Terminale/AddModel.cshtml
@model InsTerm.TERMINAL_MODEL

@{
    ViewBag.Title = "Dodaj model";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nowy model terminalu</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utwórz nowe urządzenie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.TM_ID)

        </div>

        <div class="form-group">
            @Html.Label("Nazwa modelu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TM_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TM_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Opis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TM_DESC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TM_DESC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Opis wersji", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TM_VERSION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TM_VERSION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
        <div>
            @ViewBag.Errors
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista modeli", "ModelList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/Terminale/Aplikacje.cshtml
@model IEnumerable<InsTerm.TERMINAL_APP>

@{
    ViewBag.Title = "Aplikacje";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Aplikacje</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TA_NAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TA_VERSION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TA_VENDOR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TA_DESC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TERMINAL_APP_TYPES.TAT_NAME)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TA_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TA_VERSION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TA_VENDOR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TA_DESC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TERMINAL_APP_TYPES.TAT_NAME)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TA_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TA_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TA_ID })
        </td>
    </tr>
}

</table>

InsTerm/Views/Terminale/Create.cshtml
@model InsTerm.TERMINAL

@{
    ViewBag.Title = "Nowy terminal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Utwórz nowy terminal</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@TempData["Error"]</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Terminal ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.T_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.T_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Model urządzenia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("T_MODEL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.T_MODEL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Numer seryjny", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.T_SERIAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.T_SERIAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dodatkowy opis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.T_NOTES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.T_NOTES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy urządzeń", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/Terminale/Delete.cshtml
@model InsTerm.TERMINAL

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć urządzenie?</h3>
<div>
    @if (ViewBag.Error != "")
    {
        @ViewBag.Error
    }

        <h4>@Model.T_ID</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.Label("TID")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.T_ID)
            </dd>
            <dt>
                @Html.Label("Numer seryjny")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.T_SERIAL)
            </dd>

            <dt>
                @Html.Label("Informacje")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.T_NOTES)
            </dd>

            <dt>
                @Html.Label("Model urządzenia")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TERMINAL_MODEL.TM_NAME)
            </dd>

        </dl>
        <br /><br />
                    @using (Html.BeginForm("DeleteConfirmed", "Terminale", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken();
                        <input type="hidden" name="TID" value="@Model.T_ID" />
            <div class="form-actions no-color">
                <input type="submit" value="Usuń" class="btn btn-default" /> <br /><br />
                @Html.ActionLink("Powrót do listy", "Index")
            </div>
        
    }


</div>

InsTerm/Views/Terminale/DeleteModel.cshtml
@model InsTerm.TERMINAL_MODEL

@{
    ViewBag.Title = "Usuń urządzenie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuń urządzenie</h2>

<h3>Czy na pewno chcesz usunąc urządzenie?</h3>
<div>
    <h4>Model: @Model.TM_NAME, ID: @Model.TM_ID</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Nazwa")
        </dt>
        @Html.HiddenFor(model => model.TM_ID)

        <dd>
            @Html.DisplayFor(model => model.TM_NAME)
        </dd>

        <dt>
            @Html.Label("Opis")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TM_DESC)
        </dd>

        <dt>
            @Html.Label("Wersja")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TM_VERSION)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteModelConfirmed", "Terminale", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="TM_ID" value="@Model.TM_ID" />
        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót do listy urządzeń", "ModelList")
        </div>
    }
</div>

InsTerm/Views/Terminale/Details.cshtml
@model InsTerm.TERMINAL

@{
    ViewBag.Title = "Szczegóły Terminalu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Szczegóły</h2>

<div>
    <h4>TID: @Model.T_ID</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Numer seryjny")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.T_SERIAL)
        </dd>
        <br />
        <dt>
            @Html.Label("Informacje dodatkowe")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.T_NOTES)
        </dd>


        <br />
        <dt>
            @Html.Label("Model urządzenia")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TERMINAL_MODEL.TM_NAME) <br />
            @Html.DisplayFor(model => model.TERMINAL_MODEL.TM_VERSION) <br />
            @Html.DisplayFor(model => model.TERMINAL_MODEL.TM_DESC)
        </dd>

    </dl>
</div><br/><br/>
<p>
    @Html.ActionLink("Edycja", "Edit", new { id = Model.T_ID }) |
    @Html.ActionLink("Powrót do listy terminali", "Index")
</p>

InsTerm/Views/Terminale/Edit.cshtml
@model InsTerm.TERMINAL

@{
    ViewBag.Title = "Edycja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja Terminalu</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.T_ID</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.T_ID)

        <div class="form-group">
            @Html.Label("Model", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("T_MODEL", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.T_MODEL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Numer seryjny", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.T_SERIAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.T_SERIAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dodatkowe informacje", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.T_NOTES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.T_NOTES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/Terminale/EditModel.cshtml
@model InsTerm.TERMINAL_MODEL

@{
    ViewBag.Title = "Edycja modelu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja modelu urządzenia</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.TM_NAME</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TM_ID)

        <div class="form-group">
            @Html.Label("Nazwa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TM_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TM_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Opis", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TM_DESC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TM_DESC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Wersja", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TM_VERSION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TM_VERSION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "ModelList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/Terminale/List.cshtml
@model IEnumerable<InsTerm.TERMINAL>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Terminale</h2>

<h3>@ViewBag.Error</h3>

<p>
    <pre>@Html.ActionLink("Dodaj terminal", "Create")    @Html.ActionLink("Modele Urządzeń", "ModelList")</pre>
    <!--   <pre>@Html.ActionLink("Aplikacje", "Aplikacje")</pre>-->
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("TID")
        </th>
        <th>
            @Html.DisplayName("Numer seryjny")
        </th>
        <th>
            @Html.DisplayName("Opis")
        </th>
        <th>
            @Html.DisplayName("Model")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.T_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.T_SERIAL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.T_NOTES)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TERMINAL_MODEL.TM_NAME)
        </td>
        <td>
            @Html.ActionLink("Edycja", "Edit", new { id = item.T_ID }) |
            @Html.ActionLink("Szczegóły", "Details", new { id = item.T_ID }) |
            @Html.ActionLink("Usuń", "Delete", new { id = item.T_ID })
        </td>
    </tr>
}

</table>

InsTerm/Views/Terminale/ModelDetails.cshtml
@model InsTerm.TERMINAL_MODEL

@{
    ViewBag.Title = "ModelDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Urządzenie @Model.TM_ID</h2>

<div>
    <h4>Szczegóły</h4>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model=>model.TM_ID)
        <dt>
            @Html.Label("Nazwa")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TM_NAME)
        </dd>

        <dt>
            @Html.Label("Opis")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TM_DESC)
        </dd>

        <dt>
            @Html.Label("Wersja")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TM_VERSION)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edycja", "EditModel", new { id = Model.TM_ID }) |
    @Html.ActionLink("Powrót do listy", "ModelList")
</p>

InsTerm/Views/Terminale/ModelList.cshtml
@model IEnumerable<InsTerm.TERMINAL_MODEL>

@{
    ViewBag.Title = "ModelList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista modeli dostępnych urządzeń</h2>

<p><pre>@Html.ActionLink("Utwórz nowy", "AddModel")    @Html.ActionLink("Lista Terminali", "List")</pre>
</p>

@TempData["Error"]

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nazwa modelu")
        </th>
        <th>
            @Html.DisplayName("Opis")
        </th>
        <th>
            @Html.DisplayName("Wersja")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TM_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TM_DESC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TM_VERSION)
        </td>
        <td>
            @Html.ActionLink("Edycja", "EditModel", new { id=item.TM_ID }) |
            @Html.ActionLink("Szczegóły", "ModelDetails", new { id=item.TM_ID }) |
            @Html.ActionLink("Usuń", "DeleteModel", new { id=item.TM_ID })
        </td>
    </tr>
}

</table>