InsTerm/Controllers/MController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace InsTerm.Controllers
{
    [Authorize(Roles ="Instalator,Operacje,Administrator")]
    public class MController : Controller
    {
        private DB_Entities db = new DB_Entities();

        // GET: M
        public ActionResult Index()
        {
            if(User.IsInRole("Instalator"))
            {
                var Merchant = (from m in db.MERCHANT
                                join zl in db.ZLECENIE on m.M_ID equals zl.ZL_MID
                                where zl.ZL_USER == User.Identity.Name
                                select m).ToList();
                return View(Merchant);
            }
            else
            {
                var mERCHANT = db.MERCHANT.OrderBy(m => m.M_NAME).ToList();
                return View(mERCHANT);
            }

        }

        [HttpPost]
        public ActionResult Index(string mid)
        {
            if (String.IsNullOrEmpty(mid))
                return View();

            if (User.IsInRole("Instalator"))
            {
                var merchant = (from m in db.MERCHANT
                                join zl in db.ZLECENIE on m.M_ID equals zl.ZL_MID
                                where zl.ZL_USER == User.Identity.Name
                                    && m.M_NAME.Contains(mid)
                                select m).ToList();
                if (merchant.Count() == 0) return RedirectToAction("Index");
                else if (merchant.Count() == 1) return RedirectToAction("Details", new { id = merchant.ElementAt(0).M_ID });
                else
                {
                    ViewBag.Error = "Nie odnaleziono takiego akceptanta.";
                    return View(merchant);
                }
            }
            else
            {
                var merchant = db.MERCHANT.Where(m => m.M_NAME.Contains(mid)).ToList();
                if (merchant.Count() == 0) return RedirectToAction("Index");
                else if (merchant.Count() == 1) return RedirectToAction("Details", new { id = merchant.ElementAt(0).M_ID });
                else
                {
                    ViewBag.Error = "Nie odnaleziono takiego akceptanta.";
                    return View(merchant);
                }
            }

        }


        // GET: M/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            MERCHANT mERCHANT = db.MERCHANT
                .Where(m => m.M_ID == id)
                .FirstOrDefault();
            if (mERCHANT == null)
            {
                return RedirectToAction("Index");
            }
            return View(mERCHANT);
        }

        // GET: M/Create
        [Authorize(Roles ="Operacje,Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: M/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Create([Bind(Include = "M_ID,M_NAME,M_INFO,M_CITY,M_STREET,M_STREET2,M_EMAIL,M_PHONE1,M_PHONE2")] MERCHANT mERCHANT)
        {
            MERCHANT merchant = db.MERCHANT
                     .Where(m => m.M_ID == mERCHANT.M_ID)
                     .FirstOrDefault();
            if (merchant != null)
                {
                    ViewBag.Error = "Akceptant o podanym numerze MID już istnieje.";
                    return View();
                }
            try
            {
                db.MERCHANT.Add(mERCHANT);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(mERCHANT);
            }


        }

        // GET: M/Edit/5
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            MERCHANT mERCHANT = db.MERCHANT.Where(m => m.M_ID == id).First();
            if (mERCHANT == null)
            {
                ViewBag.Error = "Nie odnaleziono Akceptanta.";
                return RedirectToAction("Index");
            }
            return View(mERCHANT);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Edit([Bind(Include = "M_ID,M_NAME,M_INFO,M_CITY,M_STREET,M_STREET2,M_EMAIL,M_PHONE1,M_PHONE2")] MERCHANT mERCHANT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mERCHANT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mERCHANT);
        }

        // GET: M/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MERCHANT mERCHANT = db.MERCHANT.Find(id);
            if (mERCHANT == null)
            {
                TempData["Error"] = "Nie odnaleziono takiego punktu.";
                return RedirectToAction("Index");
            }
            return View(mERCHANT);
        }

        // POST: M/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Operacje,Administrator")]
        public ActionResult Delete(FormCollection collection)
        {
            int id = int.Parse(collection.Get("M_ID"));

            MERCHANT mERCHANT = db.MERCHANT.Find(id);
            if (mERCHANT == null) return RedirectToAction("Index");

            int count = db.ZLECENIE.Where(z => z.ZL_MID == id).Count();
            if (count != 0)
            {
                TempData["Error"] = "Nie można usunąć punktu! Punkt jest skojarzony z co najmniej jednym zleceniem";
                return RedirectToAction("Index");
            }

            db.MERCHANT.Remove(mERCHANT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InsTerm/Views/M/Create.cshtml
@model InsTerm.MERCHANT

@{
    ViewBag.Title = "NOWY PUNKT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Utwórz</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Nowy Akceptant</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @ViewBag.Error
    <div class="form-group">
        @Html.Label("MID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_ID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Nazwa punktu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_NAME, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_NAME, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Informacje", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_INFO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_INFO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Miejscowość", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_CITY, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_CITY, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Ulica", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_STREET, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_STREET, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Ulica - dodatkowe informacje".ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_STREET2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_STREET2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_EMAIL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_EMAIL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_PHONE1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_PHONE1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Telefon dodatkowy".ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.M_PHONE2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.M_PHONE2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Utwórz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/M/Delete.cshtml
@model InsTerm.MERCHANT

@{
    ViewBag.Title = "Usuń punkt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>USUŃ Punkt @Model.M_ID</h2>

<h3>Czy na pewno chcesz usunąć punkt tego Akceptanta?</h3>
<div>
    <h4>@Model.M_NAME</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Nazwa")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.M_NAME)
        </dd>

        <dt>
            @Html.Label("Opis")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.M_INFO)
        </dd>

        <dt>
            @Html.Label("Adres")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_STREET) &nbsp;&frasl;&nbsp;
            @Html.DisplayFor(model => model.M_STREET2) &nbsp;&frasl;&nbsp;
            @Html.DisplayFor(model => model.M_CITY)
        </dd>


        <dt>
            @Html.Label("Telefon")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_PHONE1) &nbsp;&frasl;&nbsp;
            @Html.DisplayFor(model => model.M_PHONE2)
        </dd>
        <dt>
            @Html.Label("Email")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_EMAIL)
        </dd>


    </dl>

    @using (Html.BeginForm("Delete", "M", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="M_ID" value="@Model.M_ID" />
        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Powrót do listy", "Index")
        </div>
    }
</div>

InsTerm/Views/M/Details.cshtml
@model InsTerm.MERCHANT

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Szczegóły</h2>

<div>
    <h4>@Model.M_NAME</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nazwa punktu")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_NAME)
        </dd>
        <br />

        <dt>
            @Html.DisplayName("Informacje")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_INFO)
        </dd>
        <br />

        <dt>
            @Html.DisplayName("Miejscowość")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_CITY)
        </dd>
        <br />

        <dt>
            @Html.DisplayName("Ulica")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_STREET)
            <br />
            @Html.DisplayFor(model => model.M_STREET2)
        </dd>
        <br />


        <dt>
            @Html.DisplayName("E-mail")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_EMAIL)
        </dd>
        <br />


        <dt>
            @Html.DisplayName("Telefon")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.M_PHONE1)
            <br />
            @Html.DisplayFor(model => model.M_PHONE2)
        </dd>
        <br />
    </dl>
</div>
<p>
    @Html.ActionLink("Powrót do listy", "Index")

    @if (!User.IsInRole("Instalator"))
    {
        <b>&nbsp;|&nbsp;</b>
        @Html.ActionLink("Edycja danych", "Edit", new { id = Model.M_ID })
    }



</p>

InsTerm/Views/M/Edit.cshtml
@model InsTerm.MERCHANT

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja Punktu</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.M_NAME</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.M_ID)

        <div class="form-group">
            @Html.Label("Nazwa Punktu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Informacje pomocnicze", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_INFO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_INFO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Miejscowość", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_CITY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_CITY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ulica", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_STREET, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_STREET, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ulica - dodatkowe informacje".ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_STREET2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_STREET2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_PHONE1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_PHONE1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Telefon dodatkowy".ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.M_PHONE2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.M_PHONE2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz zmiany" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy akceptantów", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InsTerm/Views/M/Index.cshtml
@model IEnumerable<InsTerm.MERCHANT>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @if (!User.IsInRole("Instalator"))
    {
        @Html.ActionLink("Nowy Akceptant", "Create")

    }
    &nbsp;&nbsp;&nbsp;
    @ViewBag.Error
    @TempData["Error"]
    <br/>
    <div>
        @using (Html.BeginForm())
        {
            <input type="text" name="mid" />
            <input type="submit" value="Wyszukaj" />
        }
    </div>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nazwa")
        </th>
        <th>
            @Html.DisplayName("Informacje")
        </th>
        <th>
            @Html.DisplayName("Miejscowość")
        </th>
        <th>
            @Html.DisplayName("Ulica")
        </th>
        <th>
            @Html.DisplayName("Ulica-dodatkowe")
        </th>
        <th>
            @Html.DisplayName("Email")
        </th>
        <th>
            @Html.DisplayName("Telefon")
        </th>
        <th>
            @Html.DisplayName("Telefon2")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.M_NAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_INFO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_CITY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_STREET)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_STREET2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_EMAIL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_PHONE1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.M_PHONE2)
        </td>
        <td>
            @Html.ActionLink("Szczegóły", "Details", new { id = item.M_ID })
            @if (!User.IsInRole("Instalator"))
            {
                <b>&nbsp;|&nbsp;</b>
                @Html.ActionLink("Edycja", "Edit", new { id = item.M_ID })
                <b>&nbsp;|&nbsp;</b>
                @Html.ActionLink("Usuń", "Delete", new { id = item.M_ID })
            }

        </td>
    </tr>
}

</table>